/* This is an automatically generated file */
/* Configuration name: anonymous */
#define TAUCS_OSTYPE linux
#define TAUCS_VARIANT none
#define OSTYPE_linux
#define OSTYPE_VARIANT_none
#define TAUCS_CONFIG_DREAL
#define TAUCS_CONFIG_SREAL
#define TAUCS_CONFIG_DCOMPLEX
#define TAUCS_CONFIG_SCOMPLEX
#define TAUCS_CONFIG_GENERIC_COMPLEX
#define TAUCS_CONFIG_TIMING
#define TAUCS_CONFIG_BASE
#define TAUCS_CONFIG_MATRIX_IO
#define TAUCS_CONFIG_AMD
#define TAUCS_CONFIG_COLAMD
#define TAUCS_CONFIG_GENMMD
#define TAUCS_CONFIG_ORDERING
#define TAUCS_CONFIG_FACTOR
#define TAUCS_CONFIG_LLT
#define TAUCS_CONFIG_OOC_LLT
#define TAUCS_CONFIG_OOC_LU
#define TAUCS_CONFIG_ADVANCED_MEMORY_OPS
#define TAUCS_CONFIG_VAIDYA
#define TAUCS_CONFIG_REC_VAIDYA
#define TAUCS_CONFIG_GREMBAN
#define TAUCS_CONFIG_INCOMPLETE_CHOL
#define TAUCS_CONFIG_ITER
#define TAUCS_CONFIG_INVERSE_FACTOR
#define TAUCS_CONFIG_TESTING_PROGRAMS
#define TAUCS_CONFIG_TEST_DIRECT
#define TAUCS_CONFIG_TEST_RUN
#define TAUCS_CONFIG_TEST_ITER
#define TAUCS_CONFIG_MATRIX_GENERATORS
#define TAUCS_CONFIG_MALLOC_STUBS

